export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS_AMOUNT = 'GET_PRODUCTS_AMOUNT';
export const ADD_PRODUCTS_COST = 'ADD_PRODUCTS_COST';
export const GET_PRODUCTS_COST = 'GET_PRODUCTS_COST';
export const ADD_PRODUCT_TO_LIST = 'ADD_PRODUCT_TO_LIST';
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
