export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const GET_AMOUNT_IN_CART = 'GET_AMOUNT_IN_CART';
export const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
export const DECREASE_AMOUNT = 'DECREASE_AMOUNT';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
